# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/c_shift_ram_sync_buffer/c_shift_ram_sync_buffer.xci
# IP: The module: 'c_shift_ram_sync_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/c_shift_ram_sync_buffer/c_shift_ram_sync_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_sync_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/c_shift_ram_sync_buffer/c_shift_ram_sync_buffer.xci
# IP: The module: 'c_shift_ram_sync_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/c_shift_ram_sync_buffer/c_shift_ram_sync_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_sync_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
