# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/c_counter_binary_0_1/c_counter_binary_0.xci
# IP: The module: 'c_counter_binary_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/c_counter_binary_0_1/c_counter_binary_0.xci
# IP: The module: 'c_counter_binary_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
