# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/johnh/Desktop/IMP/IMP.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param checkpoint.writeSynthRtdsInDcp 1
set_param chipscope.maxJobs 6
set_param synth.incrementalSynthesisCache C:/Users/johnh/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-14744-DESKTOP-U9NB2CD/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/johnh/Desktop/IMP/IMP.cache/wt [current_project]
set_property parent.project_path C:/Users/johnh/Desktop/IMP/IMP.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/johnh/Desktop/IMP/IMP.cache/ip [current_project]
set_property ip_cache_permissions disable [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/imports/Desktop/divisor_inv.coe
add_files C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/imports/Desktop/IMP/divisor_inv.coe
read_verilog -library xil_defaultlib -sv {
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/Core_controller_and_top/ISP_Top.sv
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/top.v
}
read_verilog -library xil_defaultlib {
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/HSV2RGB/HSV2RGB_Top.v
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/Core_controller_and_top/ISPCore.v
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/Pixel_Sync.v
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/RGB2HSV/RGB2HSV_Top.v
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/RGB2HSV/inverse_value_ram.v
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/ALUs/ALU_REG_CTRL_IO.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/ALUs/RGB_ALU.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/ALUs/HSV_ALU.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/HSV2RGB/back_calculate_c_m.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/HSV2RGB/back_calculate_d.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/HSV2RGB/back_calculate_i.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/RGB2HSV/calculate_h.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/RGB2HSV/calculate_min_max.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/RGB2HSV/calculate_s.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/Common/delay_line.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/HSV2RGB/generate_rgb_out.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/HSV2RGB/input_pixel_flow_controller.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/ISP/RGB2HSV/pixel_flow_controller.vhd
}
read_vhdl -library xil_defaultlib {
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/DVI_Constants.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/ChannelBond.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/SyncAsync.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/SyncAsyncReset.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/ClockGen.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/GlitchFilter.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/TWI_SlaveCtl.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/EEPROM_8b.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/InputSERDES.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/OutputSERDES.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/PhaseAlign.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/ResyncToBUFG.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/SyncBase.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/TMDS_Clocking.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/TMDS_Decoder.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/TMDS_Encoder.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/dvi2rgb.vhd
  C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/new/HDMI/src/rgb2dvi.vhd
}
read_ip -quiet C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/clk_ref/clk_ref.xci
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/clk_ref/clk_ref_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/clk_ref/clk_ref.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/clk_ref/clk_ref_ooc.xdc]

read_ip -quiet C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/c_counter_binary_0_1/c_counter_binary_0.xci
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc]

read_ip -quiet c:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/ila_alu/ila_alu.xci
set_property used_in_synthesis false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/ila_alu/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/ila_alu/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/ila_alu/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/ila_alu/ila_alu_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/johnh/Desktop/IMP/IMP.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/johnh/Desktop/IMP/IMP.srcs/constrs_1/new/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/johnh/Desktop/IMP/IMP.srcs/utils_1/imports/synth_1/min_max_tb.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a35tfgg484-1 -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
