# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/c_shift_ram_17/c_shift_ram_17.xci
# IP: The module: 'c_shift_ram_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/c_shift_ram_17/c_shift_ram_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_17'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/c_shift_ram_17/c_shift_ram_17.xci
# IP: The module: 'c_shift_ram_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/c_shift_ram_17/c_shift_ram_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_17'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
