# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/clk_ref/clk_ref.xci
# IP: The module: 'clk_ref' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/clk_ref/clk_ref_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/clk_ref/clk_ref.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/clk_ref/clk_ref_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/johnh/Desktop/IMP/IMP.srcs/sources_1/ip/clk_ref/clk_ref.xci
# IP: The module: 'clk_ref' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/clk_ref/clk_ref_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/clk_ref/clk_ref.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnh/Desktop/IMP/IMP.gen/sources_1/ip/clk_ref/clk_ref_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ref'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
